# Generated by Django 4.0.5 on 2022-06-19 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_articlemodel_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleModel',
            new_name='Article',
        ),
    ]
