version: "3.8"

services:
  tigerfunk_django:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8080:8080"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - tigerfunk
